### ISSUE TITLE
dev: implement `runInstruction` for the `vm`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/cairo-vm-ts#18]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/cairo-vm-ts/issues/19
- [ ] https://github.com/kkrt-labs/cairo-vm-ts/issues/20
- [ ] https://github.com/kkrt-labs/cairo-vm-ts/issues/21
```
