### ISSUE TITLE
feat: simplify further the codebase

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/cairo-vm-ts#34]
```[tasklist]
### Tasks
- [x] make memory list of lists
- [x] stop range-checking numbers -> accept that numbers is a form of usize and they're capped by 2^53 -> alleviate codebase for this
- [x] see if pc can be a number and not a relocatable
- [x] see if we need type alias
```
